### ISSUE TITLE
Namespace issues

### ISSUE THREAD

**Issue by pampernickel** [griffithlab/GenVisR#314]
It appears that there are compatibility issues between GenVisR and gridExtra_2.3; only got this issue very recently:

`Error : object ‘rbind.gtable’ is not exported by 'namespace:gridExtra'
Error: package or namespace load failed for ‘GenVisR’`

**Comment by pampernickel** [comment]
Just confirmed the issue -- I remove gridExtra 2.3 and replaced it with 2.2.1, and GenVisR works again.

**Comment by zlskidmore** [comment]
Thanks for the report @pampernickel, I believe this is fixed on the repo branch it just hasn't been pushed up to bioconductor yet, should be up at the next nightly build.

**Comment by apuhegde** [comment]
Hello, FYI it doesn't look like it's been pushed to bioconductor yet, I still get this error.

**Comment by lidaof** [comment]
I can confirm this issue still exists, downgrade gridExtra to 2.2.1 fix this
I am using R 3.3.0
