### ISSUE TITLE
Error in heatmap_grob[["grobs"]][[ind_legend]] : no such index at level 2

### ISSUE THREAD

**Issue by glscaglione** [griffithlab/GenVisR#395]
Hello,

waterfall(brcaMAF) fails after upgrading to R.4.3.2
Issue on dockerised Rstudio (R.4.3.2 - Ubuntu 22.04.2 LTS) and also on Windows 10 Pro (R.4.3.2 or R.4.3.3 - Version 10.0.19045)

Thank you for your great work.

Regards
Gianluca

**Comment by glscaglione** [comment]
Hi,

I fixed on mac ( not tested yet on Win) by downgrading ggplot2 from version 3.5.0 to 3.4.4.

Steps:
  1. Uninstall   latest ggplot version (3.5.0 for me)
  2. Download ggplot2 v3.4.5 tar.gz file from CRAN (link here)
      https://cran.r-project.org/src/contrib/Archive/ggplot2/ggplot2_3.4.4.tar.gz
  3. In RStudio run
    install.packages( "<your_path>/ggplot2_3.4.4.tar.gz", repos = NULL, type ="source" )
   Then  load
   library(GenVisR)
   and finally test with
  waterfall(brcaMAF)
  
  It worked for me. I'll check soon on win system too.

Best Gianluca

**Comment by chrisamiller** [comment]
Thanks, Zach. 

As of right now, my version of GenVisR (1.34.0) still shows this in the man page:

```
Waterfall-class            package:GenVisR             R Documentation

Class Waterfall

Description:

An S4 class for the waterfall plot object, under development!!!
```

I see that there's a newer version that 1.34.0 on bioconductor, but at least here on github, [that "under development" line still seems to be in place](https://github.com/griffithlab/GenVisR/blob/master/man/Waterfall-class.Rd#L123C1-L124C1) making it seem like it's not ready for prime-time. Is that just something that needs to be cleaned up (and I should switch to the newer capital-w Waterfall?) 

Would also be nice to deprecate the old one if it's incompatible and not supposed to be used. Maybe throw up a warning or something?

**Comment by zlskidmore** [comment]
ah, I missed that, I cleaned up the error message but missed the docs. I'll fix that and I agree that I should've deprecated. there was a sever time crunch with bioc, but I'll bring the original function back in a deprecated state.
